#**3.2 :**

##3.2.1:From Python lists to Pytorch tensors



In [145]:
a = [1.0,2.0,1.0]

In [146]:
a[0]

1.0

In [147]:
a[2]=3.0

In [148]:
a

[1.0, 2.0, 3.0]

##3.2.2:Constructing our First tensors



In [149]:
import torch
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [150]:
a[1]

tensor(1.)

In [151]:
float(a[1])

1.0

In [152]:
a[2]=2.0
a

tensor([1., 1., 2.])

##3.2.3:Essence of Tensors



In [153]:
points=torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0


In [154]:
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [155]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [156]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [157]:
points.shape

torch.Size([3, 2])

In [158]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [159]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [160]:
points[0,1]

tensor(1.)

In [161]:
points[0]

tensor([4., 1.])

#**3.3 :**


##3.3:Indexing



In [162]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [163]:
print(some_list[:],some_list[1:4],some_list[1:],some_list[:4],some_list[:-1],some_list[1:4:2])

[0, 1, 2, 3, 4, 5] [1, 2, 3] [1, 2, 3, 4, 5] [0, 1, 2, 3] [0, 1, 2, 3, 4] [1, 3]


In [164]:
points[1:]
points[1:,:]
points[1:,0]
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [165]:
print(points[1:],points[1:,:],points[1:,0],points[None])

tensor([[5., 3.],
        [2., 1.]]) tensor([[5., 3.],
        [2., 1.]]) tensor([5., 2.]) tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


#**3.4 :**


##3.4:Named Tensors

In [166]:
img_t = torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152,0.0722])

In [167]:
batch_t = torch.randn(2,3,5,5)

In [168]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape,batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [169]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape,batch_t.shape,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [170]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw',img_t,weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw',batch_t,weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [171]:
weights_named = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [172]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns')
print('img named:',img_named.shape,img_named.names)
print('batch named:',batch_named.shape,batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [173]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape,weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [174]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape,gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [175]:
weights_aligned = weights_named.align_as(img_named)
gray_named = (img_named * weights_aligned).sum('channels')

#**3.5 :**


##3.5.3:Managing a Tensor's dtype attribute :



In [176]:
gray_plain = gray_named.rename(None)
gray_plain.shape,gray_plain.names

(torch.Size([5, 5]), (None, None))

In [177]:
double_points = torch.ones(10,2,dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)
short_points.dtype

torch.int16

In [178]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)

In [179]:
points_64=torch.rand(5,dtype=torch.double)
points_short=points_64.to(torch.short)
points_64*points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

#**3.6 :**


##3.6:Tensors of API :



In [180]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [181]:
a=torch.ones(3,2)
a_t = a.transpose(0,1)
a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

#**3.7 :**


##3.7.1:Indexing into storage :



In [182]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [183]:
points_storage = points.storage()
points_storage[0]

4.0

In [184]:
points.storage()[1]

1.0

In [185]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

##3.7.2:Modefying stored values:in-place operations :



In [186]:
a=torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

#**3.8 :**


##3.8.1:views of another tensor's storage :



In [187]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [188]:
second_point.size()

torch.Size([2])

In [189]:
second_point.shape

torch.Size([2])

In [190]:
points.stride()

(2, 1)

In [191]:
second_point=points[1]
second_point.size()

torch.Size([2])

In [192]:
second_point.storage_offset()

2

In [193]:
second_point.stride()

(1,)

In [194]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [195]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

##3.8.2:Transposing without copying :



In [196]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [197]:
points_t=points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [198]:
id(points.storage())==id(points_t.storage())

True

In [199]:
points.stride()

(2, 1)

In [200]:
points_t.stride()

(1, 2)

##3.8.3:Transposing without copying :



In [201]:
some_t=torch.ones(3,4,5)
transpose_t=some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [202]:
transpose_t.shape

torch.Size([5, 4, 3])

In [203]:
some_t.stride()

(20, 5, 1)

In [204]:
transpose_t.stride()

(1, 5, 20)

##3.8.4:Contiguous tensors :



In [205]:
points.is_contiguous()

True

In [206]:
points_t.is_contiguous()

False

In [207]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_t=points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [208]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [209]:
points_t.stride()

(1, 2)

In [210]:
points_t_cont=points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [211]:
points_t_cont.stride()

(3, 1)

In [212]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

#**3.9 :**


##3.9.1:Managing tensor's device attribute:



In [213]:
points_gpu = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])


In [214]:
points_gpu = points.to(device='cuda')

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
points_gpu=points.to(device='cuda:0')

In [ ]:
points=2*points
points_gpu=2*points.to(device='cuda')

In [ ]:
points_gpu=points_gpu+4

In [ ]:
points_cpu=points_gpu.to(device='cpu')

In [ ]:
points_gpu=points.cuda()
points_gpu=points.cuda(0)
points_cpu=points_gpu.cpu()

#**3.10 :**


##3.10:NumPy interoperability:



In [ ]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

In [ ]:
points = torch.from_numpy(points_np)

#**3.12 :**


##3.12.1:Managing tensor's device attribute:



In [218]:
!pip install h5py

In [221]:
import h5py
f=h5py.File('/content/ourpoints.hdf5','w')
dset = f.create_dataset('coords',data=points.numpy())
f.close()

OSError: Unable to synchronously create file (unable to truncate a file which is already open)

In [224]:
f=h5py.File('/content/ourpoints.hdf5','r')
dset=f['coords']
last_points=dset[-2:]

KeyError: "Unable to synchronously open object (object 'coords' doesn't exist)"

In [225]:
last_points=torch.from_numpy(dset[-2:])
f.close()

NameError: name 'dset' is not defined